import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { AppWrapper } from "../components/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WebCuaToi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppWrapper>
        <body className={inter.className}>{children}</body>
      </AppWrapper>
    </html>
  );
}
